[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/"
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "/app"